name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build project
        run: mvn clean compile

  test:
    name: Test
    runs-on: windows-latest
    needs: build  # Exécute le job Test après Build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run tests
        #run: mvn clean test -Dtest=**/Intergration/**/*
        run: mvn clean test

  clover:
    name: Clover Coverage
    runs-on: windows-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run Clover coverage
        run: ./mvnw clean -fae clover:setup test clover:aggregate clover:clover

      - name: Upload Clover Report
        uses: actions/upload-artifact@v4
        with:
          name: clover-report
          path: target/site/clover
